using Stu.Config;
using Stu.Discovery;
using Xunit;

namespace Stu.Tests.Discovery;

public class ClassNameAssemblerTests
{
    [Fact]
    public void AssemblesStaticClassNames()
    {
        var discovered = new DiscoveredUtilities(
            new HashSet<string> { "flex", "hidden", "block" },
            new HashSet<string>());

        var assembler = new ClassNameAssembler(TailwindColorFamilies.AllFamilies);
        var names = assembler.Assemble(discovered).ToList();

        Assert.Contains("flex", names);
        Assert.Contains("hidden", names);
        Assert.Contains("block", names);
    }

    [Fact]
    public void AssemblesSpacingUtilities()
    {
        var discovered = new DiscoveredUtilities(
            new HashSet<string>(),
            new HashSet<string> { "p" });

        var assembler = new ClassNameAssembler(TailwindColorFamilies.AllFamilies);
        var names = assembler.Assemble(discovered).ToList();

        Assert.Contains("p-0", names);
        Assert.Contains("p-4", names);
        Assert.Contains("p-px", names);
        Assert.Contains("p-0.5", names);
        Assert.Contains("p-96", names);
    }

    [Fact]
    public void AssemblesColorUtilitiesWithFilter()
    {
        var discovered = new DiscoveredUtilities(
            new HashSet<string>(),
            new HashSet<string> { "bg" });

        var assembler = new ClassNameAssembler(new[] { "red", "blue" });
        var names = assembler.Assemble(discovered).ToList();

        Assert.Contains("bg-red-500", names);
        Assert.Contains("bg-blue-200", names);
        Assert.Contains("bg-black", names);
        Assert.Contains("bg-white", names);
        Assert.DoesNotContain("bg-green-500", names);
        Assert.DoesNotContain("bg-slate-500", names);
    }

    [Fact]
    public void AssemblesNegativeValues()
    {
        var discovered = new DiscoveredUtilities(
            new HashSet<string>(),
            new HashSet<string> { "m" });

        var assembler = new ClassNameAssembler(TailwindColorFamilies.AllFamilies);
        var names = assembler.Assemble(discovered).ToList();

        Assert.Contains("m-4", names);
        Assert.Contains("-m-4", names);
        // m-auto is a static utility generated by UtilityDiscovery, not by the assembler
    }

    [Fact]
    public void AssemblesSizingWithFractions()
    {
        var discovered = new DiscoveredUtilities(
            new HashSet<string>(),
            new HashSet<string> { "w" });

        var assembler = new ClassNameAssembler(TailwindColorFamilies.AllFamilies);
        var names = assembler.Assemble(discovered).ToList();

        Assert.Contains("w-4", names);
        Assert.Contains("w-1/2", names);
        Assert.Contains("w-2/3", names);
    }

    [Fact]
    public void SkipsContainerQueryPrefix()
    {
        var discovered = new DiscoveredUtilities(
            new HashSet<string>(),
            new HashSet<string> { "@container" });

        var assembler = new ClassNameAssembler(TailwindColorFamilies.AllFamilies);
        var names = assembler.Assemble(discovered).ToList();

        Assert.DoesNotContain("@container", names);
    }
}
