using System.Text;
using Stu.Parsing;

namespace Stu.Output;

public class CssWriter
{
    private readonly bool _minify;

    public CssWriter(bool minify = false)
    {
        _minify = minify;
    }

    public string Write(List<CssRule> rules)
    {
        var sb = new StringBuilder();

        if (!_minify)
        {
            sb.AppendLine("/* Generated by Stu — Tailwind CSS Utility Extractor */");
            sb.AppendLine($"/* {rules.Count} rules | {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC */");
            sb.AppendLine();
        }

        foreach (var rule in rules)
        {
            if (_minify)
            {
                sb.Append(rule.Selector);
                sb.Append('{');
                sb.Append(string.Join(";", rule.Declarations.Select(d => $"{d.Property}:{d.Value}")));
                sb.Append('}');
            }
            else
            {
                sb.AppendLine($"{rule.Selector} {{");
                foreach (var decl in rule.Declarations)
                    sb.AppendLine($"  {decl.Property}: {decl.Value};");
                sb.AppendLine("}");
                sb.AppendLine();
            }
        }

        return sb.ToString();
    }

    public void WriteToFile(List<CssRule> rules, string outputPath)
    {
        var dir = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrEmpty(dir))
            Directory.CreateDirectory(dir);

        File.WriteAllText(outputPath, Write(rules));
    }
}
